# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 22:08
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='properties.City', verbose_name='cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.BooleanField(default=False, verbose_name='destaque')),
                ('intent', models.CharField(max_length=10, verbose_name='finalidade')),
                ('property_type', models.CharField(max_length=15, verbose_name='tipo de propriedade')),
                ('address', models.CharField(max_length=200, verbose_name='endereço')),
                ('area', models.CharField(max_length=30, verbose_name='área')),
                ('in_front_of', models.TextField(verbose_name='em frente a')),
                ('total_bedroom', models.IntegerField(verbose_name='dormitórios')),
                ('total_maids_room', models.IntegerField(verbose_name='dormitórios de empregada')),
                ('total_maids_wc', models.IntegerField(verbose_name='banheiros de empregada')),
                ('total_lavatory', models.IntegerField(verbose_name='lavabos')),
                ('total_dining_room', models.IntegerField(verbose_name='salas de refeição')),
                ('total_kitchen', models.IntegerField(verbose_name='cozinhas')),
                ('total_hall', models.IntegerField(verbose_name='halls')),
                ('total_service_area', models.IntegerField(verbose_name='áreas de serviço')),
                ('total_leisure_area', models.IntegerField(verbose_name='ranchos')),
                ('total_suite', models.IntegerField(verbose_name='suítes')),
                ('total_bathroom', models.IntegerField(verbose_name='banheiros')),
                ('total_living_room', models.IntegerField(verbose_name='salas de estar')),
                ('total_tv_room', models.IntegerField(verbose_name='salas de tv')),
                ('total_coffe_room', models.IntegerField(verbose_name='copas')),
                ('total_pantry', models.IntegerField(verbose_name='despensas')),
                ('total_office', models.IntegerField(verbose_name='escritórios')),
                ('total_garage', models.IntegerField(verbose_name='garagens')),
                ('total_other', models.IntegerField(verbose_name='outros')),
                ('obs', models.TextField(verbose_name='observações')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='preço')),
                ('conditions', models.CharField(max_length=50, verbose_name='condições')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='properties.City', verbose_name='cidade')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='properties.Neighborhood', verbose_name='bairro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
        ),
    ]
