# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 21:06
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0002_auto_20170615_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('featured', models.BooleanField(default=False, verbose_name='destaque')),
                ('num_record', models.IntegerField(null=True, verbose_name='ficha')),
                ('intent', models.CharField(choices=[('alugar', 'Alugar'), ('comprar', 'Comprar')], max_length=10, verbose_name='finalidade')),
                ('obs', models.TextField(blank=True, verbose_name='observações')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='preço')),
                ('conditions', models.CharField(blank=True, max_length=50, verbose_name='condições')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='endereço')),
                ('total_bedroom', models.IntegerField(default=0, verbose_name='dormitórios')),
                ('total_maids_room', models.IntegerField(default=0, verbose_name='dormitórios de empregada')),
                ('total_maids_wc', models.IntegerField(default=0, verbose_name='banheiros de empregada')),
                ('total_lavatory', models.IntegerField(default=0, verbose_name='lavabos')),
                ('total_dining_room', models.IntegerField(default=0, verbose_name='salas de refeição')),
                ('total_kitchen', models.IntegerField(default=0, verbose_name='cozinhas')),
                ('total_hall', models.IntegerField(default=0, verbose_name='halls')),
                ('total_service_area', models.IntegerField(default=0, verbose_name='áreas de serviço')),
                ('total_leisure_area', models.IntegerField(default=0, verbose_name='ranchos')),
                ('total_suite', models.IntegerField(default=0, verbose_name='suítes')),
                ('total_bathroom', models.IntegerField(default=0, verbose_name='banheiros')),
                ('total_living_room', models.IntegerField(default=0, verbose_name='salas de estar')),
                ('total_tv_room', models.IntegerField(default=0, verbose_name='salas de tv')),
                ('total_coffe_room', models.IntegerField(default=0, verbose_name='copas')),
                ('total_pantry', models.IntegerField(default=0, verbose_name='despensas')),
                ('total_office', models.IntegerField(default=0, verbose_name='escritórios')),
                ('total_garage', models.IntegerField(default=0, verbose_name='garagens')),
                ('total_other', models.IntegerField(default=0, verbose_name='outros')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('featured', models.BooleanField(default=False, verbose_name='destaque')),
                ('num_record', models.IntegerField(null=True, verbose_name='ficha')),
                ('intent', models.CharField(choices=[('alugar', 'Alugar'), ('comprar', 'Comprar')], max_length=10, verbose_name='finalidade')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='endereço')),
                ('area', models.CharField(blank=True, max_length=30, verbose_name='área')),
                ('obs', models.TextField(blank=True, verbose_name='observações')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='preço')),
                ('conditions', models.CharField(blank=True, max_length=50, verbose_name='condições')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('featured', models.BooleanField(default=False, verbose_name='destaque')),
                ('num_record', models.IntegerField(null=True, verbose_name='ficha')),
                ('intent', models.CharField(choices=[('alugar', 'Alugar'), ('comprar', 'Comprar')], max_length=10, verbose_name='finalidade')),
                ('obs', models.TextField(blank=True, verbose_name='observações')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='preço')),
                ('conditions', models.CharField(blank=True, max_length=50, verbose_name='condições')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='endereço')),
                ('total_bedroom', models.IntegerField(default=0, verbose_name='dormitórios')),
                ('total_maids_room', models.IntegerField(default=0, verbose_name='dormitórios de empregada')),
                ('total_maids_wc', models.IntegerField(default=0, verbose_name='banheiros de empregada')),
                ('total_lavatory', models.IntegerField(default=0, verbose_name='lavabos')),
                ('total_dining_room', models.IntegerField(default=0, verbose_name='salas de refeição')),
                ('total_kitchen', models.IntegerField(default=0, verbose_name='cozinhas')),
                ('total_hall', models.IntegerField(default=0, verbose_name='halls')),
                ('total_service_area', models.IntegerField(default=0, verbose_name='áreas de serviço')),
                ('total_leisure_area', models.IntegerField(default=0, verbose_name='ranchos')),
                ('total_suite', models.IntegerField(default=0, verbose_name='suítes')),
                ('total_bathroom', models.IntegerField(default=0, verbose_name='banheiros')),
                ('total_living_room', models.IntegerField(default=0, verbose_name='salas de estar')),
                ('total_tv_room', models.IntegerField(default=0, verbose_name='salas de tv')),
                ('total_coffe_room', models.IntegerField(default=0, verbose_name='copas')),
                ('total_pantry', models.IntegerField(default=0, verbose_name='despensas')),
                ('total_office', models.IntegerField(default=0, verbose_name='escritórios')),
                ('total_garage', models.IntegerField(default=0, verbose_name='garagens')),
                ('total_other', models.IntegerField(default=0, verbose_name='outros')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('featured', models.BooleanField(default=False, verbose_name='destaque')),
                ('num_record', models.IntegerField(null=True, verbose_name='ficha')),
                ('intent', models.CharField(choices=[('alugar', 'Alugar'), ('comprar', 'Comprar')], max_length=10, verbose_name='finalidade')),
                ('obs', models.TextField(blank=True, verbose_name='observações')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='preço')),
                ('conditions', models.CharField(blank=True, max_length=50, verbose_name='condições')),
                ('area', models.CharField(blank=True, max_length=30, verbose_name='área')),
                ('in_front_of', models.TextField(blank=True, verbose_name='em frente a')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
        migrations.RemoveField(
            model_name='property',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='property',
            name='user',
        ),
        migrations.AddField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.AddField(
            model_name='land',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_land', to='properties.City', verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='land',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_land', to='properties.Neighborhood', verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='land',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_land', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddField(
            model_name='house',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_house', to='properties.City', verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='house',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_house', to='properties.Neighborhood', verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='house',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_house', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_commercial', to='properties.City', verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_commercial', to='properties.Neighborhood', verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_commercial', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_apartment', to='properties.City', verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_apartment', to='properties.Neighborhood', verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_apartment', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
