# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20170615_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='total_dining_room',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='total_leisure_area',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='total_living_room',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='total_other',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='total_tv_room',
        ),
        migrations.RemoveField(
            model_name='house',
            name='total_dining_room',
        ),
        migrations.RemoveField(
            model_name='house',
            name='total_living_room',
        ),
        migrations.RemoveField(
            model_name='house',
            name='total_other',
        ),
        migrations.RemoveField(
            model_name='house',
            name='total_tv_room',
        ),
        migrations.RemoveField(
            model_name='land',
            name='in_front_of',
        ),
        migrations.AddField(
            model_name='apartment',
            name='area',
            field=models.CharField(blank=True, max_length=30, verbose_name='área'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='total_room',
            field=models.IntegerField(default=0, verbose_name='salas'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='total_bathroom',
            field=models.IntegerField(default=0, verbose_name='banheiros'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='total_garage',
            field=models.IntegerField(default=0, verbose_name='garagens'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='total_kitchen',
            field=models.IntegerField(default=0, verbose_name='cozinhas'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='total_office',
            field=models.IntegerField(default=0, verbose_name='escritórios'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='total_room',
            field=models.IntegerField(default=0, verbose_name='salas'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='total_service_area',
            field=models.IntegerField(default=0, verbose_name='áreas de serviço'),
        ),
        migrations.AddField(
            model_name='house',
            name='total_room',
            field=models.IntegerField(default=0, verbose_name='salas'),
        ),
        migrations.AddField(
            model_name='land',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='endereço'),
        ),
    ]
