# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 12:46
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('properties', '0005_auto_20170615_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image_url', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagem')),
                ('order', models.IntegerField(default=0, verbose_name='ordem')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterField(
            model_name='apartment',
            name='num_record',
            field=models.IntegerField(blank=True, null=True, verbose_name='ficha'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='num_record',
            field=models.IntegerField(blank=True, null=True, verbose_name='ficha'),
        ),
        migrations.AlterField(
            model_name='house',
            name='num_record',
            field=models.IntegerField(blank=True, null=True, verbose_name='ficha'),
        ),
        migrations.AlterField(
            model_name='land',
            name='num_record',
            field=models.IntegerField(blank=True, null=True, verbose_name='ficha'),
        ),
    ]
