# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 16:27
from __future__ import unicode_literals

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20170616_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagem')),
                ('order', models.IntegerField(default=0, verbose_name='ordem')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Land')),
            ],
        ),
        migrations.RemoveField(
            model_name='photo',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
