# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='property',
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Foto', 'verbose_name_plural': 'Fotos'},
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
