# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_auto_20170617_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image_url',
            new_name='image',
        ),
    ]
