# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_auto_20170628_1326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='House',
            new_name='HouseOld',
        ),
        migrations.RenameModel(
            old_name='Apartment',
            new_name='ApartmentOld',
        ),
        migrations.RenameModel(
            old_name='Commercial',
            new_name='CommercialOld',
        ),
        migrations.RenameModel(
            old_name='Land',
            new_name='LandOld',
        ),
    ]
