# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 16:43
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0012_auto_20170630_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('featured', models.BooleanField(default=False, verbose_name='destaque')),
                ('num_record', models.IntegerField(blank=True, null=True, verbose_name='ficha')),
                ('intent', models.CharField(choices=[('alugar', 'Alugar'), ('comprar', 'Comprar')], max_length=10, verbose_name='finalidade')),
                ('obs', models.TextField(blank=True, verbose_name='observações')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='preço')),
                ('conditions', models.CharField(blank=True, max_length=50, verbose_name='condições')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='apartmentold',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_apartmentold', to='locations.City', verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='apartmentold',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_apartmentold', to='locations.Neighborhood', verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='apartmentold',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_apartmentold', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AlterField(
            model_name='commercialold',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_commercialold', to='locations.City', verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='commercialold',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_commercialold', to='locations.Neighborhood', verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='commercialold',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_commercialold', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AlterField(
            model_name='houseold',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_houseold', to='locations.City', verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='houseold',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_houseold', to='locations.Neighborhood', verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='houseold',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_houseold', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AlterField(
            model_name='landold',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_landold', to='locations.City', verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='landold',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_landold', to='locations.Neighborhood', verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='landold',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_landold', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='properties.Property')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='endereço')),
                ('area', models.CharField(blank=True, max_length=30, verbose_name='área')),
                ('total_bedroom', models.IntegerField(default=0, verbose_name='dormitórios')),
                ('total_maids_room', models.IntegerField(default=0, verbose_name='dormitórios de empregada')),
                ('total_maids_wc', models.IntegerField(default=0, verbose_name='banheiros de empregada')),
                ('total_lavatory', models.IntegerField(default=0, verbose_name='lavabos')),
                ('total_room', models.IntegerField(default=0, verbose_name='salas')),
                ('total_kitchen', models.IntegerField(default=0, verbose_name='cozinhas')),
                ('total_hall', models.IntegerField(default=0, verbose_name='halls')),
                ('total_service_area', models.IntegerField(default=0, verbose_name='áreas de serviço')),
                ('total_suite', models.IntegerField(default=0, verbose_name='suítes')),
                ('total_bathroom', models.IntegerField(default=0, verbose_name='banheiros')),
                ('total_coffe_room', models.IntegerField(default=0, verbose_name='copas')),
                ('total_pantry', models.IntegerField(default=0, verbose_name='despensas')),
                ('total_office', models.IntegerField(default=0, verbose_name='escritórios')),
                ('total_garage', models.IntegerField(default=0, verbose_name='garagens')),
            ],
            options={
                'verbose_name_plural': 'Apartamentos',
                'verbose_name': 'Apartamento',
            },
            bases=('properties.property',),
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='properties.Property')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='endereço')),
                ('area', models.CharField(blank=True, max_length=30, verbose_name='área')),
                ('total_room', models.IntegerField(default=0, verbose_name='salas')),
                ('total_kitchen', models.IntegerField(default=0, verbose_name='cozinhas')),
                ('total_office', models.IntegerField(default=0, verbose_name='escritórios')),
                ('total_bathroom', models.IntegerField(default=0, verbose_name='banheiros')),
                ('total_garage', models.IntegerField(default=0, verbose_name='garagens')),
                ('total_service_area', models.IntegerField(default=0, verbose_name='áreas de serviço')),
            ],
            options={
                'verbose_name_plural': 'Pontos Comerciais',
                'verbose_name': 'Ponto Comercial',
            },
            bases=('properties.property',),
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='properties.Property')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='endereço')),
                ('total_bedroom', models.IntegerField(default=0, verbose_name='dormitórios')),
                ('total_maids_room', models.IntegerField(default=0, verbose_name='dormitórios de empregada')),
                ('total_maids_wc', models.IntegerField(default=0, verbose_name='banheiros de empregada')),
                ('total_lavatory', models.IntegerField(default=0, verbose_name='lavabos')),
                ('total_room', models.IntegerField(default=0, verbose_name='salas')),
                ('total_kitchen', models.IntegerField(default=0, verbose_name='cozinhas')),
                ('total_hall', models.IntegerField(default=0, verbose_name='halls')),
                ('total_service_area', models.IntegerField(default=0, verbose_name='áreas de serviço')),
                ('total_leisure_area', models.IntegerField(default=0, verbose_name='ranchos')),
                ('total_suite', models.IntegerField(default=0, verbose_name='suítes')),
                ('total_bathroom', models.IntegerField(default=0, verbose_name='banheiros')),
                ('total_coffe_room', models.IntegerField(default=0, verbose_name='copas')),
                ('total_pantry', models.IntegerField(default=0, verbose_name='despensas')),
                ('total_office', models.IntegerField(default=0, verbose_name='escritórios')),
                ('total_garage', models.IntegerField(default=0, verbose_name='garagens')),
            ],
            options={
                'verbose_name_plural': 'Casas',
                'verbose_name': 'Casa',
            },
            bases=('properties.property',),
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='properties.Property')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='endereço')),
                ('area', models.CharField(blank=True, max_length=30, verbose_name='área')),
            ],
            options={
                'verbose_name_plural': 'Terrenos',
                'verbose_name': 'Terreno',
            },
            bases=('properties.property',),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_property', to='locations.City', verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_property', to='locations.Neighborhood', verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_property', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
