# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_properties_abc_to_mti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentold',
            name='city',
        ),
        migrations.RemoveField(
            model_name='apartmentold',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='apartmentold',
            name='user',
        ),
        migrations.RemoveField(
            model_name='commercialold',
            name='city',
        ),
        migrations.RemoveField(
            model_name='commercialold',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='commercialold',
            name='user',
        ),
        migrations.RemoveField(
            model_name='houseold',
            name='city',
        ),
        migrations.RemoveField(
            model_name='houseold',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='houseold',
            name='user',
        ),
        migrations.RemoveField(
            model_name='landold',
            name='city',
        ),
        migrations.RemoveField(
            model_name='landold',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='landold',
            name='user',
        ),
        migrations.DeleteModel(
            name='ApartmentOld',
        ),
        migrations.DeleteModel(
            name='CommercialOld',
        ),
        migrations.DeleteModel(
            name='HouseOld',
        ),
        migrations.DeleteModel(
            name='LandOld',
        ),
    ]
